server:
  port: 8080
  metrics_port: 9090
  log_level: debug
  environment: development

database:
  host: localhost
  port: 5433
  name: codedoc_dev
  user: codedoc
  password: codedoc_password
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

orchestrator:
  session_timeout: 24h
  max_concurrent_sessions: 100
  worker_pool_size: 10

mcp:
  token_limit: 25000
  rate_limit:
    requests_per_minute: 100
    burst_size: 10

filesystem:
  workspace_root: ./workspace
  max_file_size: 10MB
  allowed_extensions:
    - .go
    - .py
    - .js
    - .ts
    - .java